### ISSUE TITLE
API - Run new interview session

### ISSUE THREAD

**Issue by Hamudss** [jhpyle/docassemble#141]
Is it possible to implement to send the data via POST passing values ​​in the body with json instead of sending with parameters to run new interview session in the API?

**Comment by jhpyle** [comment]
The `/api/session/new` endpoint is a GET endpoint only.
https://docassemble.org/docs/api.html#session_new
However, you do a GET call to `/api/session/new` and then immediately do a POST call to `/api/session` to set variables in the interview.
https://docassemble.org/docs/api.html#session_post
If you want to do the equivalent of setting URL parameters, you can set `variables` in the POST call to `{"url_args['first_name']": "John", "url_args['last_name']": "Smith"}`.

**Comment by Hamudss** [comment]
Can I set the user_id by this JSON?

**Comment by jhpyle** [comment]
The `user_id` is not an intrinsic variable for a session.  If a user is logged in and they navigate to an interview session (i.e., visiting a URL with `i` and `session` parameters set) then the session will henceforth be listed in their My Interviews page.  The same is true for any other user.  This is because interview sessions can be multi-user.  However, by default, interviews are encrypted by a decryption key, so you would need to set `multi_user = True` to turn off server-side encryption if you wanted anybody to be able to join the interview.
