### ISSUE TITLE
Feature Request: Javascript function that returns the url of a static file

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#153]
It would be useful to have a javascript function similar to [static_image](https://docassemble.org/docs/functions.html#static_image) that returns the url for a static file given the package name and path.

Then I can define a function in an external script like:
```
function insertCoolImage() {
    $(someElement).append($('<img src="' + path_to_file('my_cool_image.png') + '">'));
}
```

**Comment by jhpyle** [comment]
The difference is that when `static_file()` is called, the code that locates the appropriate file is aware of which block in the YAML included the result of `static_file()`.  Thus, if a block in package `docassemble.familylaw` references a file `static_file('custody_order_example.png')`, it knows to look in the `data/static` folder of the `docassemble.familylaw` package.

In the context of pure JavaScript, there is no way of knowing which package is intended as the context.  An interview can contain code from multiple different packages, and the JavaScript could originate from any of those packages.

One alternative is to write the JavaScript code inside the YAML so that you can use the `.url_for()` method inside of `${ ... }` to get the URL for a static image.

Another alternative is to link to the file within its package.  E.g., `<img src="/packagestatic/docassemble.familylaw/custody_order_example.png">`.  The only risk is that if the server has a non-standard `root` in the Configuration, this will be the wrong path.  I could provide a JavaScript function that adjusts for this problem, but it would require two arguments: a package name and a file name.

**Comment by bennlich** [comment]
Thanks for the detailed reply!

This issue came up for me specifically in the context of the playground. Does the playground have access to the normal installed packages? This kind of url didn't work for me: `<img src="/packagestatic/docassemble.familylaw/custody_order_example.png">`

**Comment by jhpyle** [comment]
Static files in the Playground are available at a URL like `/packagestatic/docassemble.playground1/custody_order_example.png`.

**Comment by bennlich** [comment]
Can playgrounds access static package files that are not uploaded through the playground UI?

**Comment by jhpyle** [comment]
Sure, anyone on the internet can access the files in `/packagestatic/`.  It simply serves files from the `data/static` directory in the designated Python package that is installed on the system.

**Comment by bennlich** [comment]
Okay. Makes sense. It looks like the issue I'm having is that the base url is treated differently in the playground and in normal-interview-land.

In the [playground](https://mycitations.uat.courts.ca.gov/interview?i=docassemble.playground1%3Aa2p-entrypoint.yml#page1):
```
/packagestatic/docassemble.jcc.abilitytopay/california-courts-logo.png
```
resolves to
```
https://abilitytopayblobtest.blob.core.windows.net/abilitytopayblobtestcontainer/playgroundstatic/1/packagestatic/docassemble.jcc.abilitytopay/california-courts-logo.png
```

In [normal-interview-land](https://mycitations.uat.courts.ca.gov/interview?i=docassemble.jcc.abilitytopay%3Adata%2Fquestions%2Finterview.yml#page1), the same absolute path resolves to:
```
https://mycitations.uat.courts.ca.gov/packagestatic/docassemble.jcc.abilitytopay/california-courts-logo.png
```

**Comment by jhpyle** [comment]
You can also access the file with
`https://mycitations.uat.courts.ca.gov/packagestatic/docassemble.playground1/california-courts-logo.png`.

This is somewhat slower than accessing the file through https://abilitytopayblobtest.blob.core.windows.net link because the file needs to be retrieved from Blob Storage and then served, but for testing purposes the speed differential probably doesn't matter very much.

**Comment by bennlich** [comment]
The problem I'm having is that the urls beginning with https://abilitytopayblobtest.blob.core.windows.net/ do not succeed.

E.g. https://abilitytopayblobtest.blob.core.windows.net/packagestatic/docassemble.jcc.abilitytopay/california-courts-logo.png

**Comment by jhpyle** [comment]
Then this is a bug report and not a feature request!

**Comment by bennlich** [comment]
Right. Going to close this and open a new issue now that we've gotten to the bottom of it.
