### ISSUE TITLE
Date Picker is not supported in IE

### ISSUE THREAD

**Issue by JCCChris** [jhpyle/docassemble#160]
Adding polyfill javascript can add support for date picking in IE.

Example polyfill scripts:
https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#web-forms-individual-input-types

**Comment by jhpyle** [comment]
It's a good suggestion, but I don't know if I want to go down the road of adding JavaScript in order to make UI enhancements for legacy browsers.

I think for now I would recommend that if anyone wants to add a polyfill on their site, they can use [`global javascript`](https://docassemble.org/docs/config.html#global%20javascript) to add it.

If there was a well-accepted standard package for dealing with such polyfills (in the way jQuery and Bootstrap, which I incorporate, are well-accepted standards), I might include it.

**Comment by JCCChris** [comment]
Modernizr detects features that are missing for any browsers that don't support them.

**Comment by JCCChris** [comment]
I will be "forced" to support IE, so if you don't plan to do it, I will use the global javascript that you've suggested.  Thank you!

**Comment by jhpyle** [comment]
Modernizr is well accepted, but my understanding is that it doesn't provide the workarounds; e.g., it doesn't provide a widely accepted UI for a date picker that works on all devices and with all languages and replicates what modern browsers provide.

IE users (and Safari desktop users) can still use date fields by typing in dates, and date validation still works.  I don't consider the absence of a date picker widget to be a lack of "support" for IE/Safari.  Date pickers only came into existence circa 2012, after all.

**Comment by JCCChris** [comment]
You're not wrong, my issue (that is actually my problem) is that there is a resistance to dropping support altogether for IE and DA does work in IE.   So, I must make things work the same for both browsers or document the differences so that they are not reported as bugs.  And, it's only this one area where the functionality differs. (from what I have experienced)  Seems like the easiest course of action for me is just to make it work the same.  But, again, this is actually my problem. 

If you are at all interested, I plan to use the open source date picker at:

http://www.javascriptkit.com/script/script2/epoch/index.shtml

 Thank you for all your help!
