### ISSUE TITLE
What to do about a big userdict table

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#167]
One of my docassemble deployments has a very large userdict table:

```
docassemble=> \dti+ userdict;
                           List of relations
 Schema |   Name   | Type  |    Owner    | Table |  Size  | Description 
--------+----------+-------+-------------+-------+--------+-------------
 public | userdict | table | docassemble |       | 965 MB | 
```
```
docassemble=> select count(*) from userdict;
 count 
-------
 35137
```

That's about 30KB per row. Is that expected?

My other deployments have smaller `userdict` tables: 15MB in ~9700 rows (1.5KB/row), and 25MB in ~1000 rows (25KB/row).

What's stored in this table? Anything I can do to save space?

**Comment by jhpyle** [comment]
That table stores the interview answers for each step of each session.  30kb per interview step does not seem large to me.

There is a cron job that cleans up old sessions.  You can change the [`interview delete days`](https://docassemble.org/docs/config.html#interview%20delete%20days) if you want to clean up old sessions more often than the default.

You could write your interview so that it ends with an `exit` button.  When the user clicks it, their interview answers will be permanently deleted.  To do this with code, you can use [`command('exit')`](https://docassemble.org/docs/functions.html#command).

You may be able to take steps to reduce the size of the data structure representing each step of interview answers.  Do a test interview on your development server, answer questions until you are near the end, then click Source -> Show variables and values.  If any of the information you see is not specific to the user, but is global data, you can stop using a variable to keep that information, and instead store the information in a Python module.  For example, if I have a list of all the counties in a state and addresses of the courthouses in each county, there is no need to store that list in the interview answers.  Instead, I can have a module with a function that returns the name of a courthouse for a given county.

**Comment by bennlich** [comment]
Thank you. I just tried out setting `interview delete days` to 14, getting into the python venv, and running:

```
python -m docassemble.webapp.cron -type cron_daily
```

This did delete a bunch of rows! However, I don't think I actually got any disk space back until I ran:
```
vacuum full;
```
from within psql.

---

> You may be able to take steps to reduce the size of the data structure representing each step of interview answers. Do a test interview on your development server, answer questions until you are near the end, then click Source -> Show variables and values. If any of the information you see is not specific to the user, but is global data, you can stop using a variable to keep that information, and instead store the information in a Python module. For example, if I have a list of all the counties in a state and addresses of the courthouses in each county, there is no need to store that list in the interview answers. Instead, I can have a module with a function that returns the name of a courthouse for a given county.

How do you store the data in the module so that it does not get included in the interview variables? I'm pretty sure if you declare a simple variable at the top of a module, it does get included. Or is that incorrect?

**Comment by jhpyle** [comment]
PostgreSQL has an autovacuum daemon, which you can see in the output of `ps` (`postgres: 9.6/main: autovacuum launcher process`)

The `modules` block has the effect of running the Python command `from themodule import *`.  This will import every name declared in your module `.py` file unless you define `__all__` inside your module, in which case only the names mentioned in the `__all__` list will be imported through `import *`.

So if your module has a function called `court_of()`, declare `__all__ = ['court_of']` in your module file.  That way you can have other global variables in the module namespace and they won't be imported into your interview answers.

**Comment by bennlich** [comment]
:+1: Thank you! I ended up going with an `_` prefix instead of an `_all_` declaration.

**Comment by jhpyle** [comment]
If your module file imports any other modules or names from other modules, and those names do not begin with the underscore, those names will be brought into your interview namespace by the `modules` block every time the screen loads.  That might be harmless aside from unnecessary CPU cycles, though.
