### ISSUE TITLE
sessions do not expire

### ISSUE THREAD

**Issue by frankyshells** [jhpyle/docassemble#174]
the session cookie is cleared from the browser once it is closed, however, the session remains valid long after that.  The session timeout should be configurable.

**Comment by jhpyle** [comment]
Docassemble uses [Flask-KVSession](https://pythonhosted.org/Flask-KVSession/).  The session expiration time is 31 days (the Flask default).  I can make this configurable in the Docassemble configuration.

Logging out sets the expire time of the cookies to 0.  Before the HTTP response that clears the cookies is returned, the contents of the Flask session object are cleared.  So if the cookie was intercepted, and someone tried to use it, they would resume the Flask session, but that wouldn't get them anything, because the contents of the session would be empty.  The application will give an empty Flask session to anyone who visits the site.

If the user does not log out, then the Flask session is not cleared.  I wouldn't want it to be cleared, either, because the server doesn't know whether the user has closed their browser or still has it open.  Maybe the user went to sleep with their browser tab open, and plans to resume the interview the next day, or the day after.  If they aren't logged in, keeping their browser open is their only way to retain access to their interview session.  So I don't see a reason to clear the Flask session except after the 31 day period (which can be configured to something else if you want a shorter period).

**Comment by jhpyle** [comment]
See [`session lifetime seconds`](https://docassemble.org/docs/config.html#session%20lifetime%20seconds) in 0.4.70.

**Comment by jhpyle** [comment]
Closing this because I think I addressed the issue but if not, it can be reopened.
