### ISSUE TITLE
Ways of rolling back a docassemble upgrade

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#191]
I believe someone already asked this question in the DA slack, but I can't remember the discussion, so I'm re-opening here for posterity.

Docassemble has an upgrade button in the admin UI. What are some ways of rolling back that upgrade if something important breaks?

My current method is to freeze docassemble dockerhub releases in my own docker image repository. Then I perform upgrades the same way I do rollbacks--by pulling down those images, killing the running container, and starting a new one.

This seems like a bit of overkill, since I really only need to be able to rollback the docassemble python package (not the entire system).

**Comment by jhpyle** [comment]
The Python packages are installed through `pip`, so you can just use the `pip` method of rolling back:
![image](https://user-images.githubusercontent.com/11341940/64058215-f4c9f880-cb75-11e9-8f0d-91ceb9f1527d.png)
Since `docassemble.webapp` depends on the same version of each of the `docassemble*` packages, this will downgrade all of the packages at once.

**Comment by bennlich** [comment]
Cool! Good to know!
