### ISSUE TITLE
Allow customization of contents of standard elements

### ISSUE THREAD

**Issue by knod** [jhpyle/docassemble#205]
As an example, I'd like to make yesnomaybe and continue buttons more language agnostic. I'd do that by adding icons, such as a check mark, either next to the text or completely replacing the text. If I could make my own contents for yes, no, and maybe buttons, I could work with other wording or fontawesome icons.

Developer's alternatives:

- Write their own yes, no, and maybe buttons for each and every question, and that's fine as a plan G or so, but that's a lot of duplication which is fragile.
- Use javascript or jQuery, but that's also an added level of complexity for the developer. Will your co-developers learn js too so they can debug it if you're not there?
- Do it with CSS. Unfortunately, CSS can't identify the contents of an element. The best shot is a `[value="whatever"]` selector, but that won't work because then it'll add that icon to every element with that selector. When there are buttons that aren't just yes, no, and maybe it'd be better for them to have more topically relevant icons.

**Comment by jhpyle** [comment]
The design of docassemble (and many web UI systems) is for UI customization to take place in JavaScript/CSS.  For example, the file upload widget is a Bootstrap plugin.  The HTML that is sent to the browser is a simple `<input type="file">` and then JavaScript transforms it into something very different.

Here is what it would look like to put Font Awesome icons in front of yes/no buttons:
```
$(document).on('daPageLoad', function(){
  $('.da-field-yesno button[value="True"]').prepend('<i class="fas fa-check mr-2">');
  $('.da-field-yesno button[value="False"]').prepend('<i class="fas fa-times mr-2">');
});
```

(This requires 0.5.24 because I found a typo in the `da-field-yesno` class name when writing it.)

The result is:
![image](https://user-images.githubusercontent.com/11341940/66438830-d6b8a900-e9fb-11e9-81e0-8393dd22b14f.png)

This JavaScript code can be put into a JavaScript file called `customyesno.js` in the Static folder of a package and included with:

```
features:
  javascript: customyesno.js
```

This file can be bundled into a package and used from other packages, and get installed through the Python dependency installation system.

The tools for creating and maintaining a customization like this are:

1. Right-click -> Inspect (to discover the `da-field-yesno` and the DOM structure)
2. jQuery (to identify the elements to modify and modify them)
3. Bootstrap (the `mr-2` class for adding some spacing)

The are very popular technologies.  Whereas customizing the UI on the server side would require detailed knowledge of how docassemble implements system-wide, interview-wide, and question-specific customizations, which is esoteric and complicated.
