### ISSUE TITLE
Not all 'invalid value' input messages triggered at the same time.

### ISSUE THREAD

**Issue by knod** [jhpyle/docassemble#209]
Even if there are multiple fields that are invalid, on the first 'submit' the invalid message is only shown for empty required fields, but it takes another submit to show the invalid messages for the fields that have triggered a function that invalidates their contents.

Can they all be triggered at the first 'submit'?

**Comment by jhpyle** [comment]
I would need to see the YAML for the `question` at issue.

There are two kinds of input validation.  One is provided in JavaScript through the JQuery Validate plugin.  The other is server-side encryption.  These two validation methods are going to trigger at different times because one is JavaScript-based and prevents the request from being sent to the server, and the other is applied after the request is sent to the server.

**Comment by knod** [comment]
That sounds like the what's happening. Is there a way Docassemble can trigger them both at the same time? Send the request to the server with a flag so that those other fields can be checked for valid values while still preserving the data that the page isn't valid?

**Comment by jhpyle** [comment]
No.
