### ISSUE TITLE
No supported "hidden" data type

### ISSUE THREAD

**Issue by JCCChris** [jhpyle/docassemble#219]
It is very helpful to have hidden fields that work the same as visible fields.  While it's possible to create custom HTML in DocAssemble, the state will be inconsistent when the user presses the back button.  Having this data available is crucial for implementing custom elements and custom HTML that works consistently through a back button/link event.

**Comment by jhpyle** [comment]
This is not going to be implemented.

**Comment by JCCChris** [comment]
Thank you for your support.  I'm sorry that I misunderstood your meaning in our previous conversations.  This misunderstanding allowed me to successfully complete my project's first phase in a way that made everyone happy since the necessary elements were far different from the stock docassemble for a critical part of the process.  I will notify my superiors that these will not be supported in the future.

**Comment by jhpyle** [comment]
There isn't any feature here that "will not be supported in the future."  Using `datatype: hidden` is not supported now and was never supported in the past.  It has always been an undocumented thing that happens to work -- a "use-at-your-own-risk" hack.  It does what it does.  As I said previously, I am not going to change the code that passes through the `datatype` to the `type` attribute of the `<input>` element, so if your interview works now I don't see any reason why it would not work in the future.

I haven't seen your code, so I have no idea what you are doing.  You should tell your superiors to allow you to share your code.  You can share it privately.  I can sign an NDA.  If I could see your code, maybe I could figure out a feature that would make sense, or I could suggest another way of accomplishing the same thing that would be elegant and maintainable.  I am perfectly happy to add additional features.  I add additional features all the time.  Tell your superiors that I am 100% willing to spend hours and hours writing code to help solve their problems, for free.  The constraint is that I only add features that make sense under the design of the system, and hidden fields in HTML happens to be something that is not consistent with the design of the system.

**Comment by JCCChris** [comment]
Not every possible combination and permutation exists in the documentation.  My mistake was that since you were the one that introduced the idea of using "datatype: hidden" to me when I was asking if hidden data types would be implemented meant that it was not a "hack".  The reason I thought it was not in the documentation was because you wanted to discourage things that are specific to HTML.  I was and am willing to accept the limitation of "only working in HTML".

**Comment by jhpyle** [comment]
The design of the system is to keep the front end in the front end and to keep the YAML as a clean specification of the substantive content and data structure.  There is quite a lot you can do within this paradigm and I have yet to see an example of an interface element that cannot be implemented within this paradigm.  For example, you wanted a date of birth selector that used select elements and I wrote JavaScript that implemented that by transforming the `<input>` element into a `type="hidden"` element.  Note that the YAML for the field did not change at all.

The `CustomDataType` class is also available, which facilitates the identification of input elements and containers by CSS class names.  I plan to expand its functionality to include support for server-side input validation and server-side data transformation.

While using `type="hidden"` is useful (see the date of birth widget JavaScript, the `datatype: ajax` JavaScript, etc.), I can't think of any reason why `datatype: hidden` would be desirable.  It is a meaningless statement because "hidden" is not a type of data.  If a variable is an integer it should have `datatype: integer` because then it will be appropriately transformed into a Python integer when it is saved.  If you use `datatype: yesno` then the value `'True'` will be transformed into the Python `True`.  But if you use `datatype: hidden` then the variable can only be a string.  It is much better to just give a field a meaningful `datatype` and then do the UI transformations in JavaScript.  You could have a `question` with six fields and use JavaScript to hide all of them, replace their `type`s with `hidden`, and then present the user with a fancy widget that uses JavaScript events to update the six different `<input>` elements.  All of this is entirely compatible with the use of the back button.  It's just UI stuff, which means it should go in JS and CSS files, not in `fields` listings in the YAML.
