### ISSUE TITLE
Feature request: "Done" button on signature field is styled differently from all other buttons

### ISSUE THREAD

**Issue by NateV** [jhpyle/docassemble#24]
The "Done" button on a signature block is styled differently from all other buttons. Its located in a different place and looks very different. If its easy to do, it'd be nice to have it styled and placed like other buttons.

**Comment by jhpyle** [comment]
The issue is that on a smartphone screen, the user will rotate the device so that the orientation is horizontal, and then they will need as much of the screen as possible to write their signature.  Scrolling is disabled because scrolling is the same movement as signing, and when scrolling is allowed the user can get themselves into a situation where half the screen is hidden and they can't get it back.  For larger screens, I could do some responsive CSS where the standard Bootstrap layout and buttons are used.  Although that could lead to a confusing situation where the buttons jump from one area of the screen to another depending on the rotation of the screen.

**Comment by NateV** [comment]
No, that makes sense. Its fine the way it is.

**Comment by jhpyle** [comment]
I implemented this suggestion in 0.1.10.
