### ISSUE TITLE
Add users without requiring email invitation

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#26]
It would be great if it were possible to add multiple users to Docassemble without requiring email setup.

**Comment by jhpyle** [comment]
Do you mean that you want to create user accounts that have a username that is not an e-mail address?

Or do you mean that you, as an administrator, would like to create user accounts through a means that does not involve the sending of an invitation e-mail to the user?

If it's the latter, what I typically do is go to `/user/register` and create accounts for people by effectively registering and logging in as them, making note of their passwords, and then I set the information in the Profile, and log out.  This process does not cause an e-mail to be sent.  I sometimes create accounts using "fake" e-mail addresses, since I know that an e-mail will not be sent unless I use an interview that sends an e-mail.

I don't have a "batch" method of adding users yet.  Maybe I could have a function under "Utilities" where you upload an Excel spreadsheet with user information, and it creates/updates accounts based on the information in the spreadsheet.

**Comment by nonprofittechy** [comment]
The second one--adding a user, as an administrator, without needing to send an email invitation. I just updated to the latest version and I see something I had trouble with before, changing the user role of someone who signed up on their own, is possible. I'm not sure why that didn't work for me before.

**Comment by jhpyle** [comment]
Yes, if you are logged in as a user who has the privileges of "admin" you should be able to go to "User List" on the menu, click on a user, and edit the user's privileges.

There is also a feature on development servers whereby users can request an upgrade of their privileges.

**Comment by jhpyle** [comment]
I added an "Add a user" feature in 0.1.39.
https://docassemble.org/docs/users.html#add
