### ISSUE TITLE
'Back' button is missing from signature page on mobile in vertical mode

### ISSUE THREAD

**Issue by plocket** [jhpyle/docassemble#300]
From what I can see, no 'Back' button appears at the bottom of the signature screen, even when the interview config says to add a 'Back' button to the screens.

**Comment by plocket** [comment]
Sorry, I was missing a piece of the information. This is specifically in mobile on vertical mode. If configuring the 'Back' button to appear doesn't trigger a back button on that page, how does an interview writer make sure there's a back button on that page?

**Comment by jhpyle** [comment]
In the same interview when the screen is small, I get this:
![image](https://user-images.githubusercontent.com/11341940/84379943-9de95900-abb4-11ea-8634-36c377d8f0c9.png)

The default behavior for screens under 768px in width is not to include a back button on the signature screen but rather to include a button that lets the user clear the signature area in case they want to redo their signature.

However, if you set `question back button: True` in `features`, a back button will be shown in place of the Clear button if the user is otherwise able to go back.

On small screens, the real estate is extremely limited, so there is no room for any additional buttons.
