### ISSUE TITLE
A new "testing mode" should allow skipping "required" questions

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#32]
While prototyping and developing interviews in the playground, it would be very useful to have a feature that lets you skip any "required" questions. This would allow for faster next/next/next until you got to the question you updated or changed. The option to test a single question would also be handy.

**Comment by jhpyle** [comment]
The only way I could think of to implement that would be to have a "testing default value" option for each field, so that in the testing mode, a default value is plugged in.  Whether the interview actually gets to the question you want to test will depend on the values that have been input until that point.

One way around the problem you describe is to develop your interview in the playground and click "Save and Run" once so that you have an interview in another tab.  Then navigate through the interview to the screen you want to edit.  Then you make changes to the relevant question block in the interview YAML and click "Save."  Then, go to the tab with the interview running in it and refresh the page with Ctrl-R.  You will see the effect of the changes you made to the question, and you won't have to start at the beginning.  There are some instances where this might not work, such as when you change mandatory code blocks that have already been executed in the test interview.

Another thing that might work is to install the iMacros browser extension and "record" yourself using the interview, starting with navigating to the URL of the interview with `&reset=1`.  Then you can save that macro and double-click it in the iMacros sidebar every time you want to get to a certain place in an interview.

**Comment by jhpyle** [comment]
See https://docassemble.org/docs/development.html#testing for a discussion of interview testing.  The testing mechanism described, which uses `lettuce` and `selenium`, can be used to fast-forward to a particular place in an interview scenario.

Another suggestion for testing individual questions is to insert a `mandatory: True` `code` block at the start of the interview that runs `force_ask('some_variable')`, where `some_variable` is the name of a variable that is defined by the question you want to inspect.  This will ask the minimum necessary questions to present the question to the user.  It might not work in certain circumstances, such as questions from a middle of a list gathering process.  See https://docassemble.org/docs/functions.html#force_ask

**Comment by jhpyle** [comment]
I am going through old issues to close them. There are a variety of ways to fast-forward. At the end of the day, a docassemble interview interview is a computer program that raises an exception and then gets re-run with different input; there is no universal way to fast-forward through that.
