### ISSUE TITLE
Help with SSL

### ISSUE THREAD

**Issue by DavidTD1** [jhpyle/docassemble#346]
I need help to install SSL on docassemble. 
I'm using AWS. (EC2)

**Comment by jhpyle** [comment]
How far did you get with the steps described in the documentation?  (https://docassemble.org/docs/docker.html#letsencrypt)

**Comment by DavidTD1** [comment]
If I choose to use let's encrypt, I have to sign up to let's encrypt web page?. 
If I use let's encrypt, I will have problems with EC2 configuration? Or it's enough to follow the steps described in the documentation?

**Comment by jhpyle** [comment]
Using EC2, Docker, and Let's Encrypt together is the easiest way to launch a server that uses SSL.

If you already have a non-SSL server running, it is not easy to switch. But it is pretty easy to get Let's Encrypt working if you start a new server with `docker run`.

Make sure you use an `env.list` file that looks something like this:
```
DAHOSTNAME=interviews.example.com
TIMEZONE=America/New_York
USEHTTPS=true
EC2=true
USELETSENCRYPT=true
LETSENCRYPTEMAIL=dev@example.com
```
Before running `docker run --env-file=env.list -d -p 80:80 -p 443:443 --stop-timeout 600 jhpyle/docassemble`, you need to make sure the machine is connected to the internet with ports 80 and 443 allowed by the firewall, and you need to make sure your DNS is configured so that your hostname (interviews.example.com in the above example) maps to the machine.

You cannot use the dynamic hostnames that EC2 gives you; you have to buy your own domain.

You don't have to sign up on Let's Encrypt's web site.

**Comment by DavidTD1** [comment]
Ok. Thank you. Actually, I'm using EC2, docker and I get SSL from AWS. Is it hard to configure docassemble with these parameters?  
I already have a interviews created. I don't want to lose it by creating a new one.

**Comment by jhpyle** [comment]
If you are using one of the "data storage" options, you won't lose anything.  https://docassemble.org/docs/docker.html#data%20storage

If you aren't using data storage, you should migrate to using some type of data storage sooner rather than later because it will be easier to download what you have created if you do it sooner.

The only thing I know how to do with AWS SSL is to put an application load balancer in front of a port-80-based docassemble machine.  Then you just need to set `behind https load balancer: true` and set your `external hostname` in your Configuration.  The downside is then you have to pay for the load balancer in addition to EC2 charges.  I don't know if there is some other way to use AWS SSL.  You could install certificates but that is annoying because then you have to remember to update them.

**Comment by DavidTD1** [comment]
I got a load balancer. So, now I need to set behind https  load balancer: true and set my external hostname and that's it? I don't have to add other configuration to use SSL ??

**Comment by jhpyle** [comment]
See https://docassemble.org/docs/config.html#behind%20https%20load%20balancer  You should make sure the load balancer sets the `X-Forwarded-*` headers, which I think it will.

**Comment by DavidTD1** [comment]
I did the configuration for Load balancer and I got this 

![HTTPS](https://user-images.githubusercontent.com/20271416/106005819-f9585080-608a-11eb-902a-f57d107b694f.png)

**Comment by jhpyle** [comment]
That suggests that you created the certificate with one hostname, attached it to your load balancer, and then you went into your DNS and pointed a different hostname to your load balancer.  The hostnames will need to match perfectly, unless AWS gave you a wildcard certificate.

**Comment by DavidTD1** [comment]
Thank you. It´s work
