### ISSUE TITLE
Slack / Questions

### ISSUE THREAD

**Issue by typkrft** [jhpyle/docassemble#395]
I just thought I would mention that the Slack Help Group link does appear to be working any longer. 

I was Curious if it's possible to fill out a docx and a pdf template then combine them into one document at the end. If so is there some guidance I can follow. I've tried looking around in the documentation, but may have missed something. 

Thanks!

**Comment by jhpyle** [comment]
Sorry, the Slack link expires every month and I forgot to update it.  It is updated now.

You can use the `pdf_concatenate()` function to combine a DOCX and a PDF into one document.

The resulting document is a `DAFile` rather than a `DAFileCollection`, so the way that it appears in the web browser is different from a normal `attachment`, which produces a `DAFileCollection`.

The basic idea is to do something like this:

```
mandatory: True
code: |
  final_screen
---
event: final_screen
question: All done
subquestion: |
  Here is your document:

  [:file-pdf: Your document](${ combined_document.url_for() })
---
code: |
  combined_document = pdf_concatenate(document_one.pdf, document_two.pdf, filename='combined_document.pdf')
---
attachment:
  variable name: document_one
  docx template file: my_docx_template.docx
---
attachment:
  variable name: document_two
  pdf template file: my_pdf_template.pdf
  fields:
    - "favorite_fruit": ${ favorite_fruit }
---
question: |
  What is your favorite fruit?
fields:
  - Fruit: favorite_fruit
```

**Comment by typkrft** [comment]
Thanks for the quick response and you work on this project.
