### ISSUE TITLE
Updating docker container does not restore postgres database

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#408]
Hi,

When updating a docker installation of docassemble (1.2.54->1.2.72), I get the following (partial) error message in the `/var/log/supervisor/initialize-stderr---supervisor-y901eykn.log`: 

```
28
29
Postgres database backup directory is /usr/share/docassemble/backup/postgres
Restoring postgres database docassemble
pg_restore: error: one of -d/--dbname and -f/--file must be specified
29.5
30
create_tables.main: starting
```

After restarting, the user database is reset to its "factory default" state, and all users and privileges I've created are gone. Looking at the [relevant part of the initialize.sh script](https://github.com/jhpyle/docassemble/blob/master/Docker/initialize.sh#L751) i wonder if the options to `pg_restore` are (no longer?) correct. It seems that one needs to also specify `-f -` to output the resulting SQL to stdout.

After copying in a backup copy of the postgres database from the most recent nightly backup, then running  `pg_restore -F c -C -c -f - docassemble|su -c psql postgres`, I was able to recreate the original database with users and privileges.

Should perhaps the following line in initialize.sh:

            pg_restore -F c -C -c $db | su -c psql postgres

be changed to this?

            pg_restore -F c -C -c -f - $db | su -c psql postgres

**Comment by jhpyle** [comment]
Thanks. This is fixed in the new version.

**Comment by staffanm** [comment]
Many thanks!

**Comment by staffanm** [comment]
I hate to reopen this, but I just did an upgrade to 1.2.81, and initialize.sh failed to restore the database. The relevant part from the initialize log:

> 29
> Postgres database backup directory is /usr/share/docassemble/backup/postgres
> Restoring postgres database docassemble
> ERROR:  database "docassemble" does not exist
> 29.5
> 30
> create_tables.main: starting

Looking at initialize.sh, maybe the [code to create the database](https://github.com/jhpyle/docassemble/blob/master/Docker/initialize.sh#L759) should come before the [code to restore the database](https://github.com/jhpyle/docassemble/blob/master/Docker/initialize.sh#L750)? I realize that `pg_restore` uses the `-C` option that should create the database, but for some reason it does not seem to work?

**Comment by jhpyle** [comment]
I just did a test of `docker stop` -> `docker rm` -> `docker run` with a Docker volume, and the SQL database was restored.  The log during the last `docker run` looked the same as yours:
```
29
Postgres database backup directory is /usr/share/docassemble/backup/postgres
Restoring postgres database docassemble
ERROR:  database "docassemble" does not exist
29.5
30
create_tables.main: starting
```
The "ERROR" comes from `pg_restore`.  It isn't really an error; it's just what Postgres reports when you try to restore from a backup file and the database referenced in the backup file does not already exist.  After reporting that error, it creates the database and restores the data.

`create_tables.main` always runs, even if the docassemble SQL database has tables in it, because it runs Alembic to add any tables or fields that are missing.

I don't know what the issue is in your case. Maybe the system version being used doesn't have the fix to `pg_restore`?  Maybe there was an unsafe shutdown?

Note that all that the PostgreSQL restoration process does is run pg_restore on the files in `backup/postgres`.  You can put whatever pg_dump files you want in that folder. Which database is actually used when docassemble starts depends on the `db` section of the configuration.

**Comment by staffanm** [comment]
I haven't been able to reproduce this on any subsequent updates, so it is possible that the previous shutdown was incomplete. Closing this now.
