### ISSUE TITLE
Iframe embedding causing infinite reload

### ISSUE THREAD

**Issue by jheyer159** [jhpyle/docassemble#421]
From a fresh install I add  `allow embedding: true` to the system configuration.

Then I load the docassemble site which is running with docker on `localhost:8080` into an iframe on `localhost:3000` and it triggers the following code to run.

<img width="625" alt="Screen Shot 2021-06-09 at 4 12 08 PM" src="https://user-images.githubusercontent.com/12436441/121423317-1f95d300-c93e-11eb-9450-545fd11d13f1.png">

This causes an infinite reload and the docassemble site will not allow me to login even when going directly to `localhost:8080` - not using an iframe.

Once I  kill the container, remove it, and restart then docassemble will work again.

Am I missing something in the system configuration or is there a better approach?

**Comment by jhpyle** [comment]
Look at the JavaScript console; there are probably messages about cookies being rejected.  If you don't have your side set up correctly, modern browsers will refuse to save cookies, especially when iframes are used.  The relevant configuration directives are `allow embedding` and `behind https load balancer`.

**Comment by jhpyle** [comment]
Using localhost:8080 is tricky.  That uses http:// and browsers have a preference for storing cross-site cookies only if https is used and the cookies have the `secure` flag set.  The best way to do iframe embedding is when both the host site and the docassemble site are using https:// and port 443.

If you really want to use embedding, I would suggest using a reverse proxy so that the embedding appears to the browser to be same-site.  Any cross-site cookies are now blocked by default in iOS unless the user affirmatively enables "tracking."

**Comment by jheyer159** [comment]
Thanks for the quick reply.  I did find where the cookie messages are showing up in the `issues` tab and mentions that `secure` requires https.   I will take your advice and go with the reverse proxy approach.
