### ISSUE TITLE
Custom Logfile

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#443]
Dear all,

 I have the need to log certain information to a file which remains even after the interview session (background: we are initiating DocuSign from Docassemble with one service user and - for internal cost allocation - need to know who initiated the Docusign transaction).

I tried file write functions in Python, but have rights issues (not allowed to write to filesystem). The `log()` function enables logging into the docassemble logs, but this is not really the right place for my info. Any other possibilities I have overlooked?

Many thanks!
Christian

**Comment by jhpyle** [comment]
Docassemble is designed to be a cloud-based application, so the idea of "logging to a file" is not really consistent with that. In a multi-server configuration, syslog-ng is used to forward log file entries from web servers to a central logging server. The configuration for syslog-ng tells syslog-ng which specific files to watch for changes. So unless you forked docassemble you couldn't modify that list of file to get it to use your own file.

A cloud-friendly way to create log messages would be to use a service like [Google's Cloud Logging](https://github.com/googleapis/python-logging).

[Writing a row to a Google Sheet](https://docassemble.org/docs/functions.html#google%20sheets%20example%20two) is an option.

If you are going to read the logs within docassemble itself, you could use [`write_record()`](https://docassemble.org/docs/functions.html#sql) to write log messages.

If you are always going to use a single-server configuration, you could use standard Python file commands to append to a file located in `/usr/share/docassemble/logs`.  The web server user will have permissions to write to that folder.  The log file will be backed up along with other docassemble log files, and the log file will be visible in Logs.  One downside is that `logrotate` will not rotate the file if it gets big.

Python has a module called `logging` that helps with logging, but if you try to use it, you might run into trouble because docassemble is already using `logging` for its own logging mechanism.

**Comment by cschwarz007** [comment]
Thanks a lot. For us (with a single server instance) logging to file is the easiest option. I hence used standard Python file functions, except that the path to the log directory in the docker image is `/usr/share/docassemble/log/` (no "s").
