### ISSUE TITLE
Dynamic Title / Subtitle & multiple interviews of the same sort at the same time

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#447]
Hi, our usage scenario is that we generate NDAs with Docassemble. The same user may have multiple NDAs (= interviews) at the same time in different stages of progress (e. g. with different contract parties).

The docassemble logic does seem to only support one interview of the same sort at the same time.
Also, in the "My interviews" list I would like to show more details on the started interview. I understand the `title` and `subtitle` logic, but both seem not to be dynamic (i. e. I can not add any information from variables).

Hence two key questions:

1. Can I allow multiple interviews of the same sort at the same time? If so, how?
2. Can I add dynamic information (information from variables that get set in the course of the interview, e. g. "NDA between Party 1 and Party 2") to the subtitle?

**Comment by jhpyle** [comment]
A user can have multiple sessions with the same `i` filename in progress on the server at the same time, and can use My Interviews to switch among them. However, because of the way cookies are used to maintain sessions while supporting features like `url_action()` links, users cannot run multiple interviews with the same `i` filename in different tabs of the same browser at the same time.

The title and subtitle can be changed dynamically with [`set_parts()`](https://docassemble.org/docs/functions.html#set_parts).

**Comment by cschwarz007** [comment]
As always many thanks - this made my day!
