### ISSUE TITLE
Stall when submitting page with long list of checkboxes

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#48]
(~ 10 is enough to trigger)

With 20+, you usually have to extend the wait time on the page multiple times.

**Comment by nonprofittechy** [comment]
I noticed when I switched the checkboxes to a series of yesnos, it sped up quite a bit! Hopefully this helps in narrowing down the issue.

**Comment by jhpyle** [comment]
The problem appears to be built in to the [jQuery Validation Plugin](https://jqueryvalidation.org/).  It takes that long because that is how long it takes to validate the form according to the code in the plugin, and the code of jQuery.  The solution is to code your own optimized JavaScript function that applies the appropriate input validation.  So much for being able to use a library!  Hooray for coding from scratch...

**Comment by jhpyle** [comment]
Try version 0.2.30 and let me know if it is still stalling.

**Comment by nonprofittechy** [comment]
It looks much faster now--happy to keep testing with longer checkboxes, but I think you solved the major issue.

**Comment by nonprofittechy** [comment]
Closing as I think the problem was resolved.
