### ISSUE TITLE
On-prem Active Directory

### ISSUE THREAD

**Issue by JenkiesSpark** [jhpyle/docassemble#51]
Hi - It would be terrific if an addition login method is added, using python-ldap, specifically private/onPrem Active Directory

**Comment by jhpyle** [comment]
I added an LDAP login feature in 0.2.32.  See [the documentation](https://docassemble.org/docs/config.html#ldap login).

Since the python-ldap package required some additional Debian packages to be installed, this feature is not going to work unless you run a fresh instance of docassemble using docker.

Or if you know how to poke around inside a Docker container you can install the libsasl2-dev and libldap2-dev packages manually, and also install python-ldap from Package Management.

**Comment by JenkiesSpark** [comment]
Great!  Thanks Jonathan!
