### ISSUE TITLE
following commands not working (what should I do?)

### ISSUE THREAD

**Issue by leonhatori** [jhpyle/docassemble#53]
sudo cp ./docassemble/Docker/docassemble-supervisor.conf /etc/supervisor/conf.d/docassemble.conf
sudo cp ./docassemble/Docker/ssl/* /usr/share/docassemble/certs/
sudo cp ./docassemble/Docker/rabbitmq.config /etc/rabbitmq/

**Comment by jhpyle** [comment]
Some possibilities I can think of:

* The supervisor application is not actually installed.
* The rabbitmq application is not actually installed.
* Your version of Linux doesn't store files in the same place as Debian/Ubuntu.
* You didn't run the mkdir command earlier to create /usr/share/docassemble/certs.
* You are not acting as `root`, but are still acting as `www-data`, which doesn't have permission.

If you can share the error message you are getting that might provide a clue.

Also, I recommend using Docker because it is a lot of work to install things yourself and prevent conflicts between supervisor and systemd or whatever your system uses.

**Comment by leonhatori** [comment]
Hi Jonathan, thanks for the answers. I was thinking about using Docker, but I wanted to understand the whole configuration. I will test the things you mentioned and return here. thanks
