### ISSUE TITLE
Sharing playgrounds

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#530]
Hi,
We work with multiple developers in the same docassemble instance. Is it possible (and if so, how) for developers to see each others playgrounds? I noted that - with the standard set-up - each playground is only visible to the user that created it.

Many thanks in advance!
Christian

**Comment by jhpyle** [comment]
Each developer could enable the Google Drive (or OneDrive) synchronization feature on their accounts so that there is a copy of their Playground on Google Drive (or OneDrive). Then in Google Drive (or OneDrive) they could share their Playgrounds with each other so that they can each see each other's work. Synchronizing to the same locations is not advisable because it could lead to developers overwriting each others' work (and I don't think Google/OneDrive allows it, either). 

GitHub can be used as a collaboration tool. Each developer could commit changes from their Playgrounds to a particular branch of a GitHub repository. For example, I have a private repository called `jhpyle/docassemble-testprivate`. I can go to my Playground Packages folder and "Pull" in the private package using `git@github.com:jhpyle/docassemble-testprivate.git` as the "GitHub URL." Then I can make changes to files and go back to the Packages page and click the GitHub button, and under "branch" I can select "(New branch)" and choose the name `jpyle` so that the branch is identified as containing my work. So I can make commits to my personal branch whenever I am ready to share my work with the team. My collaborators can see my work by browsing GitHub and checking out my branch. The maintainer can use Git to build a final version of the package by selectively merging particular files from particular branches.

A user with `admin` privileges can use [the API](https://docassemble.org/docs/api.html#playground_get) to list files and download files from any other developer's Playground.

The design of docassemble is that docassemble development is just Python development, since docassemble add-on packages are just Python packages. So whatever tools Python developers use for collaboration around building Python packages, they can use those same tools for docassemble development. That collaboration does not need to involve the Playground. The only advantage of the Playground is that testing changes is relatively quick. I only use the Playground for writing short proofs of concept; when I write longer interviews I do my work in a text editor and I use the [command-line tools](https://github.com/jhpyle/docassemblecli) to copy them to a server for testing.

**Comment by cschwarz007** [comment]
Understood and thanks for the suggestions.

**Comment by nonprofittechy** [comment]
@cschwarz007 Jonathan's summary is excellent, but just a few other thoughts in case you mean a different style of collaboration:

1. GitHub is really the best way to collaboratively work on a package. At the Suffolk LIT Lab we collaborate with many developers on one development server using GitHub. Our developers end up doing most Docassemble development in the playground as well. We work in branches and use pull requests when features are ready to merge.
2. If you just want to let one author develop a package and then have other authors use the package's API inside their own package: you can "include" and otherwise reference files in many places in Docassemble that live inside another author's playground. E.g.,

```yaml
include:
  - docassemble.playground1:shared_questions.yml
```

But it's usually better to add the files to a package, install it systemwide, and then reference the package path:

```yaml
include:
  - docassemble.MyPackageName:shared_questions.yml
```

**Comment by cschwarz007** [comment]
Hi Jonathan and Quinten,

Thanks a lot and fully understand. The scenario here is that we have about 5 new learners in docassemble (individuals that for the most part are not well versed at coding yet). Hence, it would be quite practical for them to be able to look at each others code (which involves a lot of trial and error) to jointly look for mistakes / improvement opportunities. Setting up synchronization with GitHub or the like makes things more complicated with them - they are happy to understand the docassemble environment.

I can totally relate to your suggestions, but these aim at "(semi) professional" developers IMHO...
