### ISSUE TITLE
Provide tags on docker image

### ISSUE THREAD

**Issue by ikus060** [jhpyle/docassemble#568]
Usage of latest tags is not recommended for good reason. It's unpredictable and may lead to application outage if the upgrade is not properly planned.

I would highly recommend to provide docker image with tags on docker hub to mitigate this problem.

If versioning is not properly implemented, at least a tag with a date would be enough.

**Comment by BryceStevenWilley** [comment]
Jonathan has addressed this before, in https://github.com/jhpyle/docassemble/issues/458, the reasoning being that the docassemble docker image is too large to keep around more than one image at a time on Docker Hub. Since there is only one image on Docker Hub, it doesn't quite make sense to use version specific tags, as those tags will break in < 1 week or so, given how frequently new versions of docassemble are released.
