### ISSUE TITLE
Setting default value of iterable dict

### ISSUE THREAD

**Issue by kotowick** [jhpyle/docassemble#583]
Hi there,

I'm looking to set deliverables[i].hours to the 'avg_hour' field in the deliverable_list dict. Essentially I want this field to pre-populate with the number of hours and let the user override that if needed.
```
---
code: |
  ...
  deliverables: DAList.using(object_type=DAObject, there_are_any=True)

  deliverable_list.initializeObject('roadmap', DAObject)
  deliverable_list['roadmap'].name = 'Review business and technical roadmap'
  deliverable_list['roadmap'].avg_hours = 25
  ...
---
question: Which deliverables do you require?
fields:
  - Resource Name: deliverables[i].name
    datatype: dropdown
    code: |
      deliverable_list
  - Number of hours: deliverables[i].hours
    datatype: integer
    min: 0
```

**Comment by kotowick** [comment]
@jhpyle  Is there an easy way to debug these variables? 

Right now, both dicts don't have corresponding keys. 

Ideally, these dicts would be the same. But I am not sure what code I need to get it to that point. 

Would be ideal that when a user selects a "deliverable_list" item, then the whole object is pushed to "deliverables".

**Comment by kotowick** [comment]
`---
objects:
  deliverables: DAList.using(object_type=DAObject, there_are_any=True)
  deliverable_list2: DAList
  aws_control_tower: DAObject
---
code: |
  aws_control_tower.name = 'AWS Control Tower'
  aws_control_tower.avg_hours = 20
  
  deliverable_list2.there_are_any = True
  deliverable_list2.append(aws_control_tower)
  deliverable_list2.auto_gather = False
  deliverable_list2.gathered = True
---
question: Which deliverables do you require?
fields:
  - Deliverable: deliverables[i].name
    datatype: object
    choices: deliverable_list2
  - Number of hours: deliverables[i].avg_hours
    datatype: integer
    min: 0
    default: ${ int(deliverable_list2[i].avg_hours) }
list collect: True`

But I was getting an index error:
`Interview has an error. There was a reference to a variable 'deliverable_list2[3]' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.`

When I tried `default: ${ int(deliverable_list2[0].avg_hours) }`, then it filled out the hours appropriately. 

Is it possible to just assign the whole object to deliverables[i]?
i.e
`- Deliverable: deliverables[i]`

**Comment by jhpyle** [comment]
Ok, now I think I understand what you are trying to accomplish. What you want to do is not really possible on a single screen. Docassemble is Python-based, and the Python-based logic is computed on the server. The logic is only evaluated when the first screen loads, when the user presses a button to continue to the next screen, or when the user refreshes the screen. What you are expecting would require the logic to be computed in real time while the user is looking at the screen. The average hours would need to be looked up in a list and populated into a field at the moment the user selects an item from the pull-down menu. That would require fancy JavaScript that docassemble doesn't have.

I would implement the interview this way:
```
objects:
  - deliverables: DAList.using(object_type=DAObject, there_are_any=True, complete_attribute='complete')
---
code: |
  deliverables[i].id
  deliverables[i].hours
  deliverables[i].complete = True
---
variable name: possible_deliverables
data:
  roadmap:
    name: Review business and technical roadmap
    avg_hours: 25
  baseline:
    name: Baseline assessment
    avg_hours: 5
  overhaul:
    name: Business process overhaul
    avg_hours: 250
---
question: What is your ${ ordinal(i) } deliverable?
fields:
  - Deliverable: deliverables[i].id
    code: |
      [[identifier, item['name']] for identifier, item in possible_deliverables.items()]
---
question: What is the number of hours of the deliverable for "${ possible_deliverables[deliverables[i].id]['name'] }"?
fields:
  - Number of hours: deliverables[i].hours
    datatype: integer
    min: 0
    default: |
      ${ possible_deliverables[deliverables[i].id]['avg_hours'] }
---
question: |
  Are there more deliverables?
subquestion: |
  So far, the deliverables are:
  
  % for item in deliverables:
  * ${ possible_deliverables[item.id]['name'] }, at ${ item.hours } hours
  % endfor
  
  Total hours so far: ${ sum(item.hours for item in deliverables) }
yesno: deliverables.there_is_another
---
mandatory: True
question: |
  This job will take ${ sum(item.hours for item in deliverables) } hours.
```
Here, `possible_deliverables` is a regular Python `dict` representing the menu of possible deliverables. The `deliverables` object stores an `id` reference to an item in the menu, from which various items like the name and the average number of hours can be drawn.

I would add that I don't generally recommend using `DAObject` in an interview because a `DAObject` has no textual representation. It is generally better if an object has a textual representation. A more ideal way to implement this interview is to use a .py module that contains the menu and a `Deliverable` class, which is a subclass of `DAObject`. The `Deliverable` class could then have a method `__str__()` that returned a textual representation. The menu of possible deliverables could be stored in a Google Sheet so you don't need to update the YAML when a new deliverable is available or the average number of hours changes.

**Comment by kotowick** [comment]
thanks @jhpyle .

What about something like having a multiselect, and then on the next page, it would iterate over each and set the default # of hours?

```
question: What is your ${ ordinal(i) } deliverable?
fields:
  - Deliverable: deliverables[i].id
    datatype: multiselect
    code: |
      [[identifier, item['name']] for identifier, item in possible_deliverables.items()]
```

Not sure what the "hours" page would look like.

**Comment by jhpyle** [comment]
Sure, you could use `list collect` for the hours if you did it that way. It would mean you could only have at most one of each type of deliverable, but I guess that is ok.

See below. This example uses `datatype: checkboxes` but `datatype: multiselect` (without the `none of the above` line) would work the same way.
```
objects:
  - deliverables: DAList.using(object_type=DAObject, auto_gather=False)
---
variable name: possible_deliverables
data:
  roadmap:
    name: Review business and technical roadmap
    avg_hours: 25
  baseline:
    name: Baseline assessment
    avg_hours: 5
  overhaul:
    name: Business process overhaul
    avg_hours: 250
---
code: |
  deliverables.clear()
  for item_id in possible_deliverables.keys():
    if selected_deliverables[item_id]:
      new_deliverable = deliverables.appendObject()
      new_deliverable.id = item_id
  deliverables.gathered = True
---
question: Select the deliverables
fields:
  - Deliverables: selected_deliverables
    datatype: checkboxes
    code: |
      [[identifier, item['name']] for identifier, item in possible_deliverables.items()]
    none of the above: False
    minlength: 1
---
question: How long will each deliverable take to complete?
fields:
  - Number of hours: deliverables[i].hours
    datatype: integer
    min: 0
    default: |
      ${ possible_deliverables[deliverables[i].id]['avg_hours'] }
list collect:
  enable: True
  label: |
    ${ possible_deliverables[deliverables[i].id]['name'] }
  allow append: False
  allow delete: False
---
mandatory: True
question: |
  This job will take ${ sum(item.hours for item in deliverables) } hours.
```
The idea here is that the list is considered "gathered" when the list contains all of the objects it is going to contain, even though the `hours` of each object are still undefined. The `mandatory` code block triggers the gathering of `deliverables[0].hours`, which causes a `question` to appear that defines `deliverables[0].hours` as well as `deliverables[1].hours`, etc. at the same time.

**Comment by kotowick** [comment]
@jhpyle your support is amazing, thank you. Would there be a way to allow the user to add a custom deliverable along with it's hours if what they are looking for isn't available in the list?

**Comment by jhpyle** [comment]
Here is a version that imports the database from a separate YAML file and lets the user add custom deliverables.

```
objects:
  - deliverables: DAList.using(object_type=Thing, auto_gather=False)
  - additional_deliverables: DAList.using(object_type=Thing)
---
code: |
  possible_deliverables = objects_from_file('deliverables.yaml')
---
code: |
  deliverables.clear()
  for item_id, data in possible_deliverables.items():
    if selected_deliverables[item_id]:
      new_deliverable = deliverables.appendObject()
      new_deliverable.id = item_id
      new_deliverable.name.text = data['name']
  for item in additional_deliverables:
    new_deliverable = deliverables.appendObject()
    new_deliverable.id = None
    new_deliverable.name.text = item.name.text  
  deliverables.gathered = True
---
question: Select the deliverables
fields:
  - Deliverables: selected_deliverables
    datatype: multiselect
    code: |
      [[identifier, item['name']] for identifier, item in possible_deliverables.items()]
    minlength: 1
  - "Any others?": additional_deliverables.there_are_any
    datatype: yesnoradio
---
question: |
  Tell me about the additional deliverables.
fields:
  - Description: additional_deliverables[i].name.text
list collect: True
---
question: How long will each deliverable take to complete?
fields:
  - Number of hours: deliverables[i].hours
    datatype: integer
    min: 0
    default: |
      % if deliverables[i].id:
      ${ possible_deliverables[deliverables[i].id]['avg_hours'] }
      % endif
list collect:
  enable: True
  label: |
    ${ deliverables[i] }
  allow append: False
  allow delete: False
---
mandatory: True
question: |
  The job entails ${ deliverables }.
subquestion: |
  It will take ${ sum(item.hours for item in deliverables) } hours in total.
```

The file `deliverables.yaml` is in the "sources" folder and has the following contents:

```
roadmap:
  name: Review business and technical roadmap
  avg_hours: 25
baseline:
  name: Baseline assessment
  avg_hours: 5
overhaul:
  name: Business process overhaul
  avg_hours: 250
```

I am assuming that by "multiple users could edit the same 'interview'" you are asking if multiple people could collaborate on maintaining the database of deliverables and average hours, as well as the YAML of the interview itself. (If you are actually asking whether multiple users could join a single session of an interview, there is a feature for that, involving setting `multi_user = True` and sharing the URL returned by `interview_url()`.)

The Playground is a development area for an individual developer; as the name suggests it is just a place to play around with docassemble YAML. Multiple people can have developer privileges on a docassemble server but there is no "shared file" system in the Playground. The intention is that developers will collaborate using GitHub, because GitHub has a lot of powerful features for collaboration that avoids situations where one developer's changes accidentally overwrite another developer's changes. If your goal is for non-developers to be able to maintain the deliverables list, they could do that on GitHub by clicking "edit," which creates a pull request (which a central person could then approve). But keeping the data in Google Sheets or Airtable would probably be easier.

**Comment by kotowick** [comment]
Awesome, thanks @jhpyle 

Let's say under the additional deliverables I want a field called items, which is an array. How can I add a button for people to keep adding items to this array? Ideally I want to iterate over it in a docx file.


```
question: Select the deliverables
fields:
  - Deliverables: selected_deliverables
    datatype: multiselect
    code: |
      [[identifier, item['name']] for identifier, item in possible_deliverables.items()]
    minlength: 1
  - "Any others?": additional_deliverables.there_are_any
    datatype: yesnoradio
---
question: |
  Tell me about the additional deliverables.
fields:
  - Title: additional_deliverables[i].name.text
  - Description: additional_deliverables[i].items
    input type: area
#  - "Any others?": additional_deliverables[i].items.there_are_any. <------ HERE
 #   datatype: yesnoradio
list collect: True
```

**Comment by jhpyle** [comment]
That is not possible.

**Comment by ikus060** [comment]
Would it not be possible to use javascript to achieve the computation of the average of all items ?

**Comment by jhpyle** [comment]
I am closing this issue but I realize I didn't respond to the last question. Any general purpose programming language can be used to compute an average. JavaScript runs in the front end in the browser, and in docassemble, Python runs in the back end on the server. The overall design of docassemble is to implement logic in Python, but you can use `features` -> `javascript` to add your own JavaScript if you want to run your own JavaScript in the front end.
