### ISSUE TITLE
Allow default values for variables that are undefined and detect loops

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#64]
Most show-stopping errors in my interview are when a variable is undefined, which sometimes doesn't happen until getting most of the way through the interview.

Another class of errors is a loop, where Docassemble thinks a variable is defined on a page, but it's not required on the page and the user doesn't put in an answer (normally because it is hidden by `show if` code.).

I suggest loop detection (if the same screen is shown multiple times and the variable still isn't defined) and the optional behavior to set a variable to FALSE or TRUE if the interview doesn't have a question to define it or the interview ran into a loop trying to define it. This is usually better behavior than halting the interview with an error, but not always, so it could be configurable. A warning flash should be displayed.

I have a feeling this might not be possible but it would be helpful if it could be or some other resolution for these common errors.

**Comment by jhpyle** [comment]
The `show if` feature is purely cosmetic and should not be used to model the logic of the interview.  If the definition of a variable is required, you need to write blocks that will succeed at defining the variable.

For example:
```
question: |
  What is your favorite fruit?
fields:
  - Favorite fruit: favorite_fruit
  - Favorite apple: favorite_apple
    show if:
      variable: favorite_fruit
      is: apple
---
code: |
  if favorite_fruit != 'apple':
    favorite_apple = 'not relevant'
```

If your interview ultimately will require a definition of `favorite_apple`, the `code` block is there to supersede the `question` and provide the default value, so that the `question` is not erroneously asked again.  Note that under some circumstances, asking a `question` block again, even in the very next screen, is sometimes the desired behavior, so treating such situations as erroneous would interfere with those applications.

If you want a variable to have a default value, you need to write a `code` block specifying what the default value should be and under what conditions you want that default value to be used.

You can also use logic to prevent the interview from even asking about a variable if the value of the variable is not necessary under some circumstances.  E.g.,

```
mandatory: True
question: |
  All done.
subquestion: |
  Your favorite fruit is ${ favorite_fruit }.
  % if favorite_fruit == 'apple':
  Your favorite apple is ${ favorite_apple }.
  % endif
```

Another option is to use the `showif()`, `showifdef()`, or `defined()` functions to control whether the definition of the variable will ever be sought.  The one-line if/else statement is also helpful; when I fill PDF forms, I often do things like:

```
  field code:
    - date_of_marriage: format_date(marriage.date, format="M/d/yyyy") if is_married else ''
```  

When docassemble raises an error that the interview did not provide a definition of a variable, that tells the interview author that there is a hole in the interview logic that needs to be filled.  The logic is not fully specified until those errors never happen.  Sometimes the hole in the logic is because of an unimportant variable that should just default to `""`, but other times the hole in the logic is an unanticipated combination of facts for which the application of law is unclear.  Docassemble cannot tell the difference between these two scenarios, so it raises an exception instead of trying to guess what the interview author's intention was.  

I get those errors frequently when I develop interviews, and they let me know when I have made a mistake in my interview authoring.  It is not an inconvenience for me if they happen deep in an interview because I use lettuce scripts to fast-forward to the part of the interview I want to test.
