### ISSUE TITLE
Default admin password is insecure

### ISSUE THREAD

**Issue by toolness** [jhpyle/docassemble#66]
Hello! I was going through the [hello world documentation](https://docassemble.org/docs/helloworld.html) and I logged in using the administrator credentials, but I was immediately taken to a "change password" screen that told me I had to change my password because my current one was insecure.  However, I saw no guidelines on what a properly secure password consisted of, which meant I had to fill out the form multiple times with increasingly complex passwords until one of them worked.

So I think there are actually two issues here:

1. Should logging in as admin for the purposes of making a hello world app require the user to change the password?
    * If the answer is "yes" for the sake of security, it makes me wonder if the original password should be some kind of random string that's shown in the logs or the console, to ensure that malicious actors couldn't attack unprotected Docassemble instances that haven't set their password yet.
    * If the answer is "no", maybe the built-in password should be one that already meets the secure password criteria yet is also easy to remember?

2. It seems like the "change password" form should have the actual definition of a secure password somewhere in it, so users don't have to repeatedly fill out the form until it accepts their new password.

**Comment by jhpyle** [comment]
The definition of a secure password appears in the text that comes up when an invalid password is entered.  The text on the change password page can be [customized](https://docassemble.org/docs/config.html#customization) so that users know what the complexity requirements are before they pick a password.

The password complexity requirements can also be [customized](https://docassemble.org/docs/config.html#password%20complexity).

If it is a security concern that the admin password is set to `password` initially, the admin password can be [set in advance](https://docassemble.org/docs/config.html#default%20admin%20account) using a configuration file that is either made part of the docker repository or installed on S3/Azure Blob Storage prior to system initialization.
