### ISSUE TITLE
Build a Markdown to RichText converter

### ISSUE THREAD

**Issue by jhpyle** [jhpyle/docassemble#72]
It would be nice to be able to insert Markdown-formatted text into .docx template files.  Maybe this could be accomplished with a function that converts Markdown to [RichText](https://docxtpl.readthedocs.io/en/latest/#richtext).

If someone wanted to figure out the function, I could figure out how to insert it into docassemble.

**Comment by epompeii** [comment]
Are you concerned about maintaining/transferring style from the markdown or just the contents?

**Comment by jhpyle** [comment]
Yes, the style would need to be reproduced.  The `docxtpl` package is fairly small; it just wraps around the `docx` package and the `jinja2` package.  The function would take Markdown as a string and return a `docx` [Run](http://python-docx.readthedocs.io/en/latest/api/text.html#run-objects) object (or maybe a list of Runs, or maybe just raw XML) representing the text.

**Comment by epompeii** [comment]
I've been exploring both hand rolling a solution and libraries to use.
My inclination is to use a library, and pandoc seems like a swiss army knife of a solution (http://pandoc.org/).
It's written in Haskell and can run on Windows, Mac, and Linux. We would be able to convert to either docx or to RTF from many different flavors of markdown. Docassemble uses CommonMark, right?

There is a Python wrapper, pypandoc (https://github.com/bebraw/pypandoc) which would allow us to either use a wheel, conda, a library call within pypandoc, or manual install.
I imagine either of the first three options would be viable here.

Does Docassemble use wheels or conda already?
What is your preference towards or away from adding additional dependencies?
Please, let me know your thoughts on where to go from here.

**Comment by jhpyle** [comment]
Docassemble already uses Pandoc elsewhere, so Pandoc is a possibility, but there are a couple of problems:
1. Pandoc is slow; we'd have to launch an external process just to convert some text, which could slow down the user interface.
2. Pandoc produces a whole docx file, while the `python-docx-template` and `docx` packages work with the RichText data type or raw XML; the file would have to be unzipped and the relevant XML for the paragraphs would need to be extracted from the XML file for the document.

Perhaps an alternative approach is to use a Markdown-to-HTML converter (a function for which exists in docassemble already) and then convert the HTML tags to XML tags.

For conversion to HTML, I am using the flavor of Markdown supported by https://python-markdown.github.io/

For Markdown-to-PDF document assembly, I am using the flavor of Markdown supported by Pandoc. 

For me, the priority is just to handle simple Markdown stuff, like paragraphs, bold, italic, hyperlinks, section headings, so that people can write templates in Markdown and inject them into docx template files.  It doesn't need to handle fancy stuff, like nested lists.  Even Pandoc doesn't handle the fancy stuff in a way that people find acceptable, so they would use a Word subdocument instead.

**Comment by epompeii** [comment]
Ah! I looked at the dependency/package list, and I didn't see it.
Sorry for not continuing my search to the repo or the documentation.
Is docassemble/docassemble_base/docassemble/base/pandoc.py your own wrapper then?

Python-Markdown does look promising as an intermediary if we go that route.
I see that libxml2 and libxslt1.1 are along with their developer packages already included as dependencies, but I didn't turn up any actual implementation. I imagine they are dependencies of other packages that are in use, such as lxml.

I haven't been able to pin down where lxml is implemented either though.
Using lxml would put us in a very similar situation performance wise to using Pandoc I imagine, as it will be relying on calls to wrapped C processes.
The plus side is that the Markdown->HTML->XML processing would be insertable directly into the output file, alleviating your second point.

Does Pandoc handle the fillable fields for Markdown-to-PDF differently? I imagine since fillable fields is a native feature of PDF that it is less of a workaround for Pandoc to get the job done there than in docx.

**Comment by jhpyle** [comment]
Pandoc doesn't fill PDFs, to my knowledge; it creates them from scratch by converting Markdown to LaTeX and then typesetting the LaTeX into a PDF.  I fill PDF fields using pdftk.

Using pypandoc (or my own wrapper, pandoc.py) would be slow because it calls `subprocess` to run the Pandoc code every time.  By contrast, libraries wrapped to C processes are very fast, probably even faster than pure Python code.  So I have no worries about using lxml or whatever Python library is appropriate for working with XML.

The Python package called `markdown` has a nice and fast Markdown-to-HTML converter.  Converting the resulting HTML to docx-style XML might just be a matter of a bunch of `re.sub` statements.  Alternatively, maybe there are some libraries that would allow you to crawl the HTML and construct XML in a recursive way.

**Comment by epompeii** [comment]
Thank you for all of the background info!
It seems like using ``markdown`` to do Markdown-to-HTML and then using ``lxml`` to aid parse the HTML-to-XML would work. 
Down the road if we want to do more intense parsing something like ``Beautiful Soup`` may be useful.

Your documentation for setting things up and doing interview development is exquisite!
I'm curious though what your development environment looks like. I have a dev instance set up on EC2 currently, and I have started to play around with these additions there.
Please, let me know if you have any suggestions.

**Comment by jhpyle** [comment]
For this project, you could probably do all the development in a standalone .py file that runs `docxtpl` on a .docx file.

But if you want to put the code directly into docassemble, the development environment I use on my Debian Linux laptop is:
1) Docassemble installed on laptop per the [manual installation instructions](https://docassemble.org/docs/installation.html), using supervisor instead of systemd for apache and celery.
2) GitHub repository cloned to my home folder;
3) After making changes to the files in the GitHub repository, I install them by doing a) `su root` b) `su www-data` c) `source /usr/share/docassemble/local/bin/activate` d) `pip install --no-deps --no-index --upgrade -r requirements.txt && touch /usr/share/docassemble/webapp/docassemble.wsgi` where requirements.txt is:

        ./docassemble
        ./docassemble_base
        ./docassemble_webapp
        ./docassemble_demo

If I will be running docassemble background processes, I do `supervisorctl start reset` as root, which restarts both the web server and Celery.  (`touch`ing the wsgi file restarts the web server only.)

**Comment by epompeii** [comment]
Awesome! I'll try and get things working independently and then give it a shot at integrating it into docassemble.
And thank you for all of the details!

**Comment by epompeii** [comment]
I pushed up my changes.
I am able to run do the conversions when just saving things to disk. Where do you think would be the best place to offer this functionality in the webapp?

**Comment by epompeii** [comment]
I pushed up a version that should solve this issue.
Also, I was trying to include my test cases, and I couldn't quite get the include statement right.
When trying to place a test python file in docassemble_base/tests, I kept getting something like this:
``ImportError: No module named docassemble.base.file_docx``

**Comment by jhpyle** [comment]
Maybe you aren't running Python inside the virtualenv?

Anyway, that code looks good!  I tested it and the bold/italic seems to be working fine.  The hyperlinks work but don't have any styling (which is an issue I've seen before in other contexts; I'm not sure what to do about that; it may depend on LibreOffice version).  Once list itemization turns on, it doesn't seem to turn off, and it also plugs in additional hyphens.  
[the_file.pdf](https://github.com/jhpyle/docassemble/files/2318007/the_file.pdf)

**Comment by epompeii** [comment]
That was definitely something that I was forgetting, but now for the same input it just says:
```ModuleNotFoundError: No module named 'docassemble'```

I've pushed my test files up this time, so we don't talk past each other. Also, I've included the pdf version here in case the docx is displayed differently for you.
[markdown_to_docx_filled.pdf](https://github.com/jhpyle/docassemble/files/2318596/markdown_to_docx_filled.pdf)
A strange thing that I noticed is that sometimes I had to delete the output file in order to get my changes to write. So just a heads up on that.

I was seeing a similar issue you were having (with the extra tabs and -) when trying to do Paragraph Lists. Also when doing simple lists, the formatting such as bold and underline wouldn't appear (though links would still be there). It seems the \t as part of the text to be formatted text broke things. I made a change that adds the \t as a different rt.add() call and that fixed it!
So you can now use a single format for a bullet point and the entire bullet point. If you have anything before or after this formatting, it will be tabbed over as a separate bullet. I played around with trying to keep state on the depth since the ul or ol tag, but what matters is if there is information in between not how far it is from the parent tag in the DOM.

**Comment by epompeii** [comment]
Both yes and no. The algorithm tries not to reinvent the wheel, and in doing so it forms a strong dependence to the output of ``markdown``, which creates [nicely formatted XHTML](https://python-markdown.github.io/reference/#output_format) by default.
This is the output that I get from ``markdown`` for my third test file: [markdown_output.txt](https://github.com/jhpyle/docassemble/files/2343562/markdown_output.txt)
GitHub does not support me attaching HTML/XHTML here, so that's why its a .txt file.

Is there an issue with the newlines that are there? Or were you just running into issues trying to clean things up?

**Comment by jhpyle** [comment]
In Markdown, single newlines should be treated as spaces and double newlines should be treated as paragraph breaks.  But it appears that the algorithm puts a paragraph break wherever there is any newline in the source.

**Comment by epompeii** [comment]
Ah! That's interesting then. ``markdown`` includes a single newline as a newline character within the output instead of interpreting it as a space. They have added (an extension)[https://python-markdown.github.io/extensions/nl2br/] that adds breaks in so that single newlines can explicitly be line breaks in HTML, which apparently is the style here on GitHub.
I would need to do more digging, but do you think that is an error on the part of Python-Markdown or just a design choice? If it's the former then it may be worth me bringing it up upstream.

Either way, I have a simple regex fix that I'll be pushing up here shortly that replaces the offending single newlines with spaces.

**Comment by jhpyle** [comment]
Since HTML has the same newline=space rule, I think `markdown`'s treatment of newlines is a feature and not a bug.  It is nice when HTML files aren't wide; it makes them easier to read.  If `markdown` did convert the newlines to spaces in the HTML output, that would be fine too.  Either way, the HTML works the same.

**Comment by epompeii** [comment]
That makes sense. It definitely helps to increase readability and mitigate the amount of side scrolling one has to do.
The change that I pushed up should match this newline=space behavior. My regex skills are still far from stellar though, so there may be a more efficient way to do it than I came up with.

**Comment by jhpyle** [comment]
I merged the pull request (locally until I publish a new version), which fixes the weird line break in the block quote.

I think what you were going for is a negative lookbehind assertion:
```
>>> import re
>>> test_text = """\
... <p>Hello world</p>
... <p>Goodbye,
... cruel world!</p>"""
>>> print test_text
<p>Hello world</p>
<p>Goodbye,
cruel world!</p>
>>> print re.sub(r'(?<!\>)\n', ' ', test_text)
<p>Hello world</p>
<p>Goodbye, cruel world!</p>
```

The broader issue is relying on newlines in the HTML to decide when to break a line in .docx.  In HTML, a line break on the screen should happen when there is a new `<p>`, or when there is a `<br>`, or there is a new `<li>`, etc.  If `markdown` happens to pass through newlines from the source into the HTML, and those newlines happen to correspond to expected line breaks in the .docx, that will make some test files work, but it could lead to weird behavior in production, because it is relying on a serendipitous incidental phenomenon rather than the meaning of the HTML tags. 

Also, it seems that closing tags on things like italic, bold, and headers are not being noticed, and bullets are added both before and after a list item.  Here is the result of [markdown-template.yml](https://github.com/jhpyle/docassemble/blob/master/docassemble_demo/docassemble/demo/data/questions/examples/markdown-template.yml): 
[the_file.pdf](https://github.com/jhpyle/docassemble/files/2346686/the_file.pdf)

So if the closing tag issue can be sorted out, then it wouldn't need to use newlines in the HTML to decide when to insert a line/paragraph break in the HTML.

**Comment by epompeii** [comment]
Thanks! That is much more succinct! 

I was playing around with keeping state on the depth so I could tell the difference between:
<p><em>This is bold <i>and italics text</i> for you to read.</b></p>
and
<p><em><i>an italics text</i></b></p>
But I opted to trust the newlines in ``markdown`` instead. Lesson learned!

It seems like it would be easier though just to go the re.sub route. I'll work on it, and I'll look into what you are seeing!

**Comment by epompeii** [comment]
So my first step was to try and reproduce the output that you were seeing, and so far I have been unable to.

Here are the input file (should be .md not .txt):
[markdown_template.txt](https://github.com/jhpyle/docassemble/files/2347112/markdown_template.txt)
And the output (docx and pdf):
[markdown_to_docx_filled.docx](https://github.com/jhpyle/docassemble/files/2347113/markdown_to_docx_filled.docx)
[markdown-template.pdf](https://github.com/jhpyle/docassemble/files/2347114/markdown-template.pdf)

The discrepancy may be related to trusting the newline output of ``markdown`` as we discussed, so I'll work on stripping the provided newlines out and generating them ourselves.

**Comment by jhpyle** [comment]
What template docx file are you using?

**Comment by epompeii** [comment]
Essentially the same template as before: [markdown_to_docx_template.docx](https://github.com/jhpyle/docassemble/files/2351119/markdown_to_docx_template.docx)

**Comment by jhpyle** [comment]
I have been using `markdown_to_docx()`, called from the `__unicode__` method of `DATemplate` and `DALazyTemplate` in `docassemble_base/docassemble/base/core.py`.  So I have not been using `test_markdown_to_docx()`.  However, even when the lines of code are the same, I get a result where the closing tags seem to be ignored.

How exactly are you generating that PDF?  In your fork, `test_markdown_to_docx()` references the `markdown` module, but the `markdown` module is not imported into the namespace.  Maybe the code that makes it work is not all in file_docx.py?

By looking at the code, it seems like it wouldn't handle nested tags.  The code seems to be saying that if any parent of an element is an LI or BLOCKQUOTE, insert a tab.  So if there is italics inside a block quote, an additional tab is inserted in the middle of the block quote?

**Comment by epompeii** [comment]
I appreciate all of the advice! And I definitely agree that making use of BeautifulSoup for most of the heavy lifting is the best way to go. The only regular expression I am using is to remove the single newlines. After thinking through it some more I found that I could use the existing spacing to inform the proper indentation for lists, paragraph lists, and blockquotes. These should now all work with an arbitrary amount of formatting! (It turns out I was way overthinking things)

While going to test my recent changes I think I may have found our culprit in integration: [html_names](https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/file_docx.py#L102)
Post merge, the dictionary html_names ended up outside of the method [add_to_rt](https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/file_docx.py#L120). This means that it was not being reinitialized every time a ``parsed`` object was dequeued. The phantom (or apparent lack of) closing tags was due to the ``bool``s still being set to ``True`` by previous ``parsed`` objects.

I'll be pushing the updated version here shortly for you to have a look, and I'll also try my hand at running it on the full system.

**Comment by epompeii** [comment]
Hey @jhpyle,
Is there anything that I can do to help finish up the work here and close out this ticket?

**Comment by jhpyle** [comment]
There are some more aspects of Markdown that could be implemented if you have time:

* Numbered lists
* Nested lists
* Indenting all lines of a block quote

**Comment by epompeii** [comment]
Is the ability to mix arbitrary list types, when nesting, something that you want to cover?
Also is there a depth limit that you want to set or would you prefer to handle arbitrary depth?
I'll definitely look into the block quote. I thought that got solved with the last algorithm tweak.

Looking over the [documentation](https://docassemble.org/docs/documents.html#docx%20template%20file), it still says:

> Note that you cannot use Markdown formatting syntax in text that you insert into a .docx file. If you do, it will pass through literally. Apply all of your formatting in the .docx template file.

What is the current status of the previous changes? Are they still just a test function?

**Comment by jhpyle** [comment]
I don't think supporting a mixing of list types is important, although with the right recursive function for converting HTML to .docx XML, this might be supported without special coding.

Regarding levels of nesting, I always follow the adage "There are only three numbers in Computer Science. Zero, One and N."  So I would handle arbitrary levels of nesting.
 
The function is live, although I haven't updated the documentation about it.  You can test it with the [markdown-template.yml](https://demo.docassemble.org/interview?i=docassemble.demo:data/questions/examples/markdown-template.yml) test script.

**Comment by epompeii** [comment]
I'll take another look into the .docx format and see what I can do.

And that's definitely the correct view of things! My concern was preventing something analogous to the lines of a [Billion Laughs Attack](https://en.wikipedia.org/wiki/Billion_laughs_attack). There aren't namespaces in Markdown though, so this is probably a moot concern.

Thanks for the link! I'll try my hand at testing my changes in a full dev environment this time around.

**Comment by jhpyle** [comment]
This has been implemented.
https://docassemble.org/docs/documents.html#markdown%20to%20docx
