### ISSUE TITLE
Enhance signature feature by allowing additional questions on signature page

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#86]
Two enhancements that I would like would be much more user-friendly if we could add additional buttons or fields on the signature page.

1. On the signature screen, it would be nice to have the option to skip the digital signature. The interview author could handle this by inserting `/s/Client Name` in the final document, which is permitted as an e-signature in many jurisdictions.

2. A very useful enhancement would be a button on the signature screen that sends a link to the user's mobile device (via SMS or email) to that they can sign on the phone, and then return to the full screen interview on a desktop browser. Clicking "send to mobile" on the desktop would advance to a screen where it refreshed periodically to wait for the mobile signature to finish. I think this would be possible using existing features of Docassemble, but so much more usable if there was the ability to add the button to the signature page.

**Comment by jhpyle** [comment]
Regarding the first item, I bypass signatures in a number of different circumstances.  Sometimes this involves inserting a blank line so that the user can print and provide a wet signature, or inserting "/s/," or inserting "<this is where your signature will go>."  I use a `template` block for the text, which results in an object of class `DATemplate`, which has the convenient feature that if you call `.show(width=2in)` on it (as you would do for the result of a `signature`), it just inserts the content of the template.  It is easy to insert some logic into the guided interview that uses the `signature` block variable if the user is ready to use the touch screen, and uses the `template` block variable otherwise.

Regarding the second item, I'll think about how to facilitate such processes in an interview so that it is easy for the interview author to set it up.

Regarding adding buttons to the `signature` block, the problem is that there is no available real estate on a smartphone screen.  The stuff that is there already (a clear button, a message, a submit button, and some text above and below the signature box) is already too much.  Scrolling the page to see additional content is incompatible with using the screen to sign your name.  So the logic and processes need to be on other screens.

**Comment by jhpyle** [comment]
Regarding the second item (which I had forgotten about, sorry), I added a recipe for it:
https://docassemble.org/docs/recipes.html#hybrid
