### ISSUE TITLE
Export "Variables" as json

### ISSUE THREAD

**Issue by tbrooke** [jhpyle/docassemble#9]
I found where Docassemble stores variable data as a Python dictionary but a json export or API would be nice to export data to an external database such as a practice management system or even just between interviews. This could be a simple json text file.

**Comment by jhpyle** [comment]
I added a function [`variables_as_json()`](http://docassemble.org/docs/functions.html#variables_as_json) that causes an HTTP response to be returned that contains the interview variables in JSON format.  This is not a perfect representation of the interview variables because the interview variables can contain objects that are not JSON serializable, like Python [sets](https://docs.python.org/2/library/stdtypes.html#set), [datetime.datetime](https://docs.python.org/2/library/datetime.html) objects, and **docassemble** [objects](http://docassemble.org/docs/objects.html).  The `variables_as_json()` function does the best it can, which should be good enough for most simple API applications.

It is probably better to be selective about which variables to make available through an API, though.  The documentation for [`response()`](http://docassemble.org/docs/functions.html#response) contains an example that uses [`json.dumps()`](https://docs.python.org/2/library/json.html) to return a JSON representation of particular variables.

I have not created a general-purpose "answer file" system because there are so many things that could go wrong if users could upload arbitrary data into an interview.  There are better solutions to the problem of sharing variables between interviews.

For example, if you have a suite of family law interviews, you can package them as a single interview with up-front questions that determine which interview to run.  The [`include`](http://docassemble.org/docs/initial.html#include) feature facilitates the incorporation of sub-interviews. 

Another way to transfer variables from one interview to another is through the [`interview_url()`](http://docassemble.org/docs/functions.html#interview_url) and [`url_args`](http://docassemble.org/docs/special.html#url_args) features.  Interview 1 can contain a question with a hyperlink to Interview 2 (using the `i` parameter to `interview_url()`), where relevant variables are passed as URL parameters to Interview 2.  Then both interviews will share the same session key.

Another way for interviews to interact with one another is through the use of [`write_record()`](http://docassemble.org/docs/functions.html#sql) and `read_record()`.  Authors can create keys based on the user's e-mail, which can be retrieved with [`user_info()`](http://docassemble.org/docs/functions.html#user_info).  Each interview, when it starts, could use `read_record()` to query whether any global information already exists.  The advantage of this method is that the data are Python-serialized rather than JSON-serialized, so Python objects can be shared.

**Comment by jhpyle** [comment]
I also added a function [`all_variables()`](http://docassemble.org/docs/functions.html#all_variables) that returns the variables as a Python dictionary in a format suitable for JSON serializing.

**Comment by tbrooke** [comment]
Thanks I will try these

**Comment by jhpyle** [comment]
I believe this issue has been addressed, so I am closing it.
